name: Test pipelines

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.8

    - name: Install package manager
      uses: abatilo/actions-poetry@v2.1.0
      with:
        poetry-version: 1.1.4

    - name: Install dependencies
      run: poetry install

    - name: Dependency security check
      run: poetry run safety check

    - name: Check for syntax errors
      run: poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test
      run: poetry run pytest

    - name: Lint
      run: |
        # exit-zero treats all errors as warnings
        poetry run flake8 . --count --statistics

    - name: Code security check
      run: poetry run bandit -r data_pipelines/*

    - name: Validate code formatter
      run: poetry run black . --check
